
export const SIGNIN = 'SIGNIN'
export const SIGNUP = 'SIGNUP'
export const LOCALSTORAGE_USER = 'LOCALSTORAGE_USER'


export const GET_POST_START = 'GET_POST_START'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'
export const GET_POST_FAILED = 'GET_POST_FAILED'


export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'


export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'


export const CREATE_POST_START = 'CREATE_POST_START'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED'

export const DELETE_POST_START = 'DELETE_POST_START'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED'

export const EDIT_POST_START = 'EDIT_POST_START'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAILED = 'EDIT_POST_FAILED'

export const LIKE_START = 'LIKE_START'
export const LIKE_SUCCESS = 'LIKE_SUCCESS'
export const LIKE_FAILED = 'LIKE_FAILED'

export const GET_LIKED_START = 'GET_LIKED_START'
export const GET_LIKED_SUCCESS = 'GET_LIKED_SUCCCESS'
export const GET_LIKED_FAILED = 'GET_LIKED_FAILED'

export const COMMENT_START = 'COMMENT_START'
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'
export const COMMENT_FAILED = 'COMMENT_FAILED'

export const DELETE_COMMENT_START = 'DELETE_COMMENT_START'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED'

export const GET_COMMENT_START = 'GET_COMMENT_START'
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS'
export const GET_COMMENT_FAILED = 'GET_COMMENT_FAILED'

export const GET_USER_POST_START = 'GET_USER_POST_START'
export const GET_USER_POST_SUCCESS = 'GET_USER_POST_SUCCESS'
export const GET_USER_POST_FAILED = 'GET_USER_POST_FAILED'


export const GET_USERS_START = 'GET_USERS_START'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCCESS'
export const GET_USERS_FAILED = 'GET_USERS_FAILED'


export const FOLLOW_START = 'FOLLOW_START'
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS'
export const FOLLOW_FAILED = 'FOLLOW_FAILED'


export const UNFOLLOW_START = 'UNFOLLOW_START'
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS'
export const UNFOLLOW_FAILED = 'UNFOLLOW_FAILED'


export const GET_FOLLOWING_START = 'GET_FOLLOWING_START'
export const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS'
export const GET_FOLLOWING_FAILED = 'GET_FOLLOWING_FAILED'


export const GET_FOLLOWERS_START = 'GET_FOLLOWERS_START'
export const GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS'
export const GET_FOLLOWERS_FAILED = 'GET_FOLLOWERS_FAILED'



export const GET_CHAT_USERS_START = 'GET_CHAT_USERS_START'
export const GET_CHAT_USERS_SUCCESS = 'GET_CHAT_USERS_SUCCESS'
export const GET_CHAT_USERS_FAILED = 'GET_CHAT_USERSG_FAILED'



export const SEND_MESSAGE_START = 'SEND_MESSAGE_START'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED'

export const RECIVE_MESSAGE_START = 'RECIVE_MESSAGE_START'
export const RECIVE_MESSAGE_SUCCESS = 'RECIVE_MESSAGE_SUCCESS'
export const RECIVE_MESSAGE_FAILED = 'RECIVE_MESSAGE_FAILED'

export const CREATE_CHAT_START = 'CREATE_CHAT_START'
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS'
export const CREATE_CHAT_FAILED = 'CREATE_CHAT_FAILED'


export const GET_MESSAGES_START = 'GET_MESSAGES_START'
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED'

export const CLEAR_CHAT_STATE = 'CLEAR_CHAT_STATE'




export const SOCKET_CONNECT_START = 'SOCKET_CONNECT_START'
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS'
export const SOCKET_CONNECT_FAILED = 'SOCKET_CONNECT_FAILED'

export const SOCKET_DISCONNECT_START = 'SOCKET_DISCONNECT_START'
export const SOCKET_DISCONNECT_SUCCESS = 'SOCKET_DISCONNECT_SUCCESS'
export const SOCKET_DISCONNECT_FAILED = 'SOCKET_DISCONNECT_FAILED'


export const RECIVE_NOTIFICATION_START = 'RECIVE_NOTIFICATION_START'
export const RECIVE_NOTIFICATION_SUCCESS = 'RECIVE_NOTIFICATION_SUCCESS'
export const RECIVE_NOTIFICATION_FAILED = 'RECIVE_NOTIFICATION_FAILED'


export const GET_NOTIFICATIONS_START = 'GET_NOTIFICATIONS_START'
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
export const GET_MSG_NOTIFICATIONS_SUCCESS = 'GET_MSG_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED'


export const REMOVE_ALL_NOTIFICATIONS_START = 'REMOVE_ALL_NOTIFICATIONS_START'
export const REMOVE_ALL_NOTIFICATIONS_SUCCESS = 'REMOVE_ALL_NOTIFICATIONS_SUCCESS'
export const REMOVE_ALL_NOTIFICATIONS_FAILED = 'REMOVE_ALL_NOTIFICATIONS_FAILED'


export const REMOVE_NOTIFICATION_START = 'REMOVE_NOTIFICATION_START'
export const REMOVE_NOTIFICATION_SUCCESS = 'REMOVE_NOTIFICATION_SUCCESS'
export const REMOVE_MSG_NOTIFICATIONS_SUCCESS = 'REMOVE_MSG_NOTIFICATIONS_SUCCESS'
export const REMOVE_NOTIFICATION_FAILED = 'REMOVE_NOTIFICATION_FAILED'



export const RELAM_CONNECT_START = 'RELAM_CONNECT_START'
export const RELAM_CONNECT_SUCCESS = 'RELAM_CONNECT_SUCCESS'
export const RELAM_CONNECT_FAILED = 'RELAM_CONNECT_FAILED'

export const GET_SEARCH_START = 'GET_SEARCH_START'
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS'
export const GET_SEARCH_FAILED = 'GET_SEARCH_FAILED'



export const SET_FIND_PEOPLE_OPEN = 'SET_FIND_PEOPLE_OPEN'
export const SET_POSTS_OPEN = 'SET_POSTS_OPEN'
export const SET_FOLLOWING_OPEN = 'SET_FOLLOWING_OPEN'
export const SET_SEARCH_OPEN = 'SET_SEARCH_OPEN'
