
export const GET_POST = 'GET_POST'
export const AUTH = 'AUTH'
export const SIGNIN = 'SIGNIN'
export const SIGNUP = 'SIGNUP'
export const LOCALSTORAGE_USER = 'LOCALSTORAGE_USER'

export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'


export const CREATE_POST_START = 'CREATE_POST_START'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED'

export const DELETE_POST_START = 'DELETE_POST_START'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED'

export const EDIT_POST_START = 'EDIT_POST_START'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAILED = 'EDIT_POST_FAILED'

export const LIKE_START = 'LIKE_START'
export const LIKE_SUCCESS = 'LIKE_SUCCESS'
export const LIKE_FAILED = 'LIKE_FAILED'

export const GET_LIKED_START = 'GET_LIKED_START'
export const GET_LIKED_SUCCESS = 'GET_LIKED_SUCCCESS'
export const GET_LIKED_FAILED = 'GET_LIKED_FAILED'

export const COMMENT_START = 'COMMENT_START'
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'
export const COMMENT_FAILED = 'COMMENT_FAILED'

export const GET_COMMENT_START = 'GET_COMMENT_START'
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS'
export const GET_COMMENT_FAILED = 'GET_COMMENT_FAILED'

export const GET_USER_POST_START = 'GET_USER_POST_START'
export const GET_USER_POST_SUCCESS = 'GET_USER_POST_SUCCESS'
export const GET_USER_POST_FAILED = 'GET_USER_POST_FAILED'


export const GET_USERS_START = 'GET_USERS_START'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCCESS'
export const GET_USERS_FAILED = 'GET_USERS_FAILED'


export const FOLLOW_START = 'FOLLOW_START'
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS'
export const FOLLOW_FAILED = 'FOLLOW_FAILED'


export const GET_FOLLOWING_START = 'GET_FOLLOWING_START'
export const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS'
export const GET_FOLLOWING_FAILED = 'GET_FOLLOWING_FAILED'


export const GET_CHAT_USERS_START = 'GET_CHAT_USERS_START'
export const GET_CHAT_USERS_SUCCESS = 'GET_CHAT_USERS_SUCCESS'
export const GET_CHAT_USERS_FAILED = 'GET_CHAT_USERSG_FAILED'



export const SEND_MESSAGE_START = 'SEND_MESSAGE_START'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED'

export const RECIVE_MESSAGE_START = 'RECIVE_MESSAGE_START'
export const RECIVE_MESSAGE_SUCCESS = 'RECIVE_MESSAGE_SUCCESS'
export const RECIVE_MESSAGE_FAILED = 'RECIVE_MESSAGE_FAILED'

export const CREATE_CHAT_START = 'CREATE_CHAT_START'
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS'
export const CREATE_CHAT_FAILED = 'CREATE_CHAT_FAILED'


export const GET_MESSAGES_START = 'GET_MESSAGES_START'
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED'

export const CLEAR_CHAT_STATE = 'CLEAR_CHAT_STATE'

export const SET_FIND_PEOPLE_OPEN = 'SET_FIND_PEOPLE_OPEN'
export const SET_POSTS_OPEN = 'SET_POSTS_OPEN'
export const SET_FOLLOWING_OPEN = 'SET_FOLLOWING_OPEN'


