export const CREATE_POST = 'CREATE_POST'
export const GET_POST = 'GET_POST'
export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'
export const SIGNIN = 'SIGNIN'
export const SIGNUP = 'SIGNUP'
export const LOCALSTORAGE_USER = 'LOCALSTORAGE_USER'